//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hotelreservation.user;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotelreservation.user package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotelreservation.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserRegistrationRequest }
     * 
     * @return
     *     the new instance of {@link UserRegistrationRequest }
     */
    public UserRegistrationRequest createUserRegistrationRequest() {
        return new UserRegistrationRequest();
    }

    /**
     * Create an instance of {@link UserRegistrationResponse }
     * 
     * @return
     *     the new instance of {@link UserRegistrationResponse }
     */
    public UserRegistrationResponse createUserRegistrationResponse() {
        return new UserRegistrationResponse();
    }

    /**
     * Create an instance of {@link UserLoginRequest }
     * 
     * @return
     *     the new instance of {@link UserLoginRequest }
     */
    public UserLoginRequest createUserLoginRequest() {
        return new UserLoginRequest();
    }

    /**
     * Create an instance of {@link UserLoginResponse }
     * 
     * @return
     *     the new instance of {@link UserLoginResponse }
     */
    public UserLoginResponse createUserLoginResponse() {
        return new UserLoginResponse();
    }

    /**
     * Create an instance of {@link NewReservationRequest }
     * 
     * @return
     *     the new instance of {@link NewReservationRequest }
     */
    public NewReservationRequest createNewReservationRequest() {
        return new NewReservationRequest();
    }

    /**
     * Create an instance of {@link NewReservationResponse }
     * 
     * @return
     *     the new instance of {@link NewReservationResponse }
     */
    public NewReservationResponse createNewReservationResponse() {
        return new NewReservationResponse();
    }

}
